[build]
  base = "org-chart-app"
  publish = "dist/org-chart-app"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
